### ISSUE TITLE
Can't resize window on Safari

### ISSUE THREAD

**Issue by bioinfbloke** [Taylor-CCB-Group/MDV#50]
Can't resize chart windows on Safari on MacOS

**Comment by xinaesthete** [comment]
Yes, I had noticed this a while ago. Just been looking into it, and not managed to fix it with CSS.

Seems like the chart content is obscuring the `::resizer` pseudo-element. ChatGPT informed me that I'd need to use `::-webkit-resizer` to apply styling to that in Safari... which appears to be correct... but unfortunately when I try to add any properties to that, it disappears.

So it seems like it might require a JS solution.

FWIW, when in grid-stack mode, there's a custom element for the resize handle, rather than CSS `resize: both`, and that does work ok.

**Comment by xinaesthete** [comment]
Removing `.cieview-chart-panel{display: flex}` makes the resizer appear in Safari, but with other bad effects on chart layouts. Should be fairly close to getting a working solution now that this is identified, though.
