### ISSUE TITLE
multitext binary data

### ISSUE THREAD

**Issue by will-moore** [Taylor-CCB-Group/MDV#64]
I'm trying to understand how to format `multitext` data, using https://mdv.molbiol.ox.ac.uk/projects/mdv_project/7012?view=Gene+Ontology example

Looking at https://github.com/Taylor-CCB-Group/MDV/blob/cc97f7ae2148b2df5363cecf22efe0397214ba18/python/mdvtools/csv_to_static.py#L186
it looks like `text` and `multitext` are processed the same way.

But I think that the values in `multitext` can be multiple values, separated by a comma.
E.g. "GO Cellular Component" column defined like this:

```
        "datatype": "multitext",
        "name": "GO cellular component",
        "field": "GO cellular component",
        "values": [
          "apicolateral plasma membrane",
          "nucleoplasm",
          "cytosol:,
...
```

Can have column data that appear to be multiple values separated by a comma. I don't know what the input data looks like (what the separator is) but in the MDV app it looks like this in the table:

<img width="512" alt="Screenshot 2023-11-01 at 23 16 01" src="https://github.com/Taylor-CCB-Group/MDV/assets/900055/ef3aa15e-dcc1-4e00-bf63-5f62bb06db4b">

But in https://github.com/Taylor-CCB-Group/MDV/blob/cc97f7ae2148b2df5363cecf22efe0397214ba18/python/mdvtools/csv_to_static.py#L108
I don't see any handling of separators.

E.g. if my input `col` list is `["cytosol,nucleus", "cytosol", "nucleus"]`, I get these 3 column values, instead of just `["cytosol", "nucleus"]`:

```
>>> colvals = ["cytosol,nucleus", "cytosol", "nucleus"]
>>> get_text_indices(colvals)
([1, 0, 2], ['cytosol', 'cytosol,nucleus', 'nucleus'])
```

So the numbers that are served as the binary data are just 1 integer per table cell, rather than multiple integers to represent the multi-text values per table cell.

What does the input and output look like for multitext columns?

**Comment by xinaesthete** [comment]
I've been meaning to review the `multitext` stuff a bit more, but I think it is indeed intended that the example you give is treated as three distinct values. Multi-text was implemented by @martinSergeant around the same time as I implemented `TagModel.ts` (neither of us quite realising the overlap at the time I think). I implemented that on top of regular `text`, with certain operations for interactively editing a dedicated `__tags` column while enforcing things like `"cytosol,nucleus"` and `"nucleus , cytosol"` ending up as the same value.

I never really got 'round to making a very nice UI for it, and actually there's a bit of a discrepancy in that at some point it occurred to me maybe `;` might be a better separator to avoid confusion when processing `csv` files - we may want to add a field to specify what the separator character is.

One thing to note is that `csv_to_static.py` should probably be removed at this point, or we should review how it's mentioned in the docs - I made it partly because I had some minor issues with `mdvproject.py`... so it hasn't been actively maintained to add things like this.

**Comment by will-moore** [comment]
Thanks for the reply, but I don't think I'm understanding very well...

If I look at https://mdv.molbiol.ox.ac.uk/projects/mdv_project/7012?view=Gene+Ontology
I can see various `row charts` such as `GO Cellular Component`:

![Screenshot 2023-11-03 at 12 20 05](https://github.com/Taylor-CCB-Group/MDV/assets/900055/a365ac86-69f6-44a2-a3e5-e41e55fc07ff)

Some image rows of the table above have values like `cytoplasm, plasma membrane, synapse`, but there is no row of that row chart that has the value of `cytoplasm, plasma membrane, synapse` because these 3 components are split up into 3 separate values.

There are 35 cellular components in that row chart, which correspond to the 35 values in the column definition JSON:

```
"datatype": "multitext",
        "name": "GO cellular component",
        "field": "GO cellular component",
        "values": [
          "apicolateral plasma membrane",
          "nucleoplasm",
          "cytosol",
...
```

And each of the 1400 data rows can be in multiple components. So the binary data must have some way of indicating which of those 35 components they are in.
If this were just a `text` column, then a value of `1` would indicate `"nucleoplasm"`, but with `multitext` there must be some way to indicate `nucleoplasm` AND `cytosol`?

**Comment by martinSergeant** [comment]
The multitext is described [here](https://github.com/Taylor-CCB-Group/MDV/blob/main/docs/extradocs/datasource.md#datatype---unique)
There may be a better way of representing such data, as its very ineffecient if some rows have many values and others have only a few or none at all
I like Pete's idea, but even if you had an int64, you are limited to 64 values and in the case GO ontologies there are thousands of values, which can occur in any combination . 
Both the python and JavaScript code have methods for converting strings into the binary format. At the moment, a comma is hard coded  as the delimiter. However I am currently dealing with GWAS traits, some of which contain commas, so I have modified the code,  so that you can specify the delimiter (but not yet pushed it up) for cases such as this when the individual values contain commas

**Comment by will-moore** [comment]
Thanks - working fine now 👍
