### ISSUE TITLE
data in datasources.json not converted to text

### ISSUE THREAD

**Issue by will-moore** [Taylor-CCB-Group/MDV#65]
I'm trying to serve the `data` within the `datasources.json` columns (instead of loading the binary `data` on the fly.
This is working fine for `integer` columns, but not for `text` columns where the data integers are not getting converted into `text` values:
In this example, I have a `text` column with `"values": ["bar", "foo"]` but these values seem to be ignored and instead I just see the data `1, 0` etc in the table:

The `datasources.json` is pasted in below the screenshot. Any idea what I need to do here? Thanks!

<img width="873" alt="Screenshot 2023-11-28 at 23 28 35" src="https://github.com/Taylor-CCB-Group/MDV/assets/900055/70e8985f-1591-4db5-a44b-271da9233585">

```
[
    {
        "name": "mdv_config_19679",
        "size": 12,
        "columns": [
            {
                "name": "Image",
                "field": "Image",
                "datatype": "integer",
                "data": [
                    706,
                    707,
                    752,
                    754,
                    755,
                    756,
                    853,
                    854,
                    855,
                    856,
                    857,
                    858
                ]
            },
            {
                "name": "Dataset_Name",
                "datatype": "text",
                "data": [
                    1,
                    1,
                    1,
                    0,
                    1,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0
                ],
                "values": [
                    "bar",
                    "foo"
                ],
                "field": "Dataset_Name"
            }
        ]
    }
]
```

**Comment by will-moore** [comment]
OK, so after reading the docs again and testing it, I realise that I can just pass in the array of actual string values for a `text` column, but I'm still not sure what to provide for a `multitext` column?

**Comment by martinSergeant** [comment]
You can include the data in the datasources config for but this would be inefficient for large datasets, 
The format for each datatype is explained [here](https://github.com/Taylor-CCB-Group/MDV/blob/main/docs/extradocs/datasource.md#column-data) but I should make it clearer that the javascript array is the format that the datastore expects.
For multitext You can specify a another delimiter instead of a comma, although I haven't documented this yet
You can use javascript arrays in the dataloader as well -[dataloaders](https://github.com/Taylor-CCB-Group/MDV/blob/main/docs/extradocs/dataloader.md)
Normally how would you request data from Omero -  I am not sure I inderstood the key/value pairs

**Comment by will-moore** [comment]
I'm not writing any JavaScript to interact with MDV, I'm just returning JSON data to AJAX requests that it's making.
I'm loading the Key-Value pairs from OMERO using the Python API, then marshalling that into the JSON format expected by MDV. Mostly I've been omitting the `data` from `datasources.json` response and instead supplying it as binary data when MDV loads it on the fly via `*.b` URLs.
